name: "dbt_wade"
version: "1.0.0"
config-version: 2

profile: "dbt_wade"

model-paths: ["models"]
macro-paths: ["macros"]

models:
  dbt_wade:
    +pre-hook:
      - "{{ configure_minio() }}"
    bronze:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
